import { GHANA_REGIONS } from './ghanaRegions'

type GhanaRegion = (typeof GHANA_REGIONS)[number]

/**
 * Major towns/cities per Ghana region, used as the destination-town dropdown
 * for door-to-door courier checkout (intra-city Bolt Send/Yango Delivery and
 * inter-city ShaQ Express). Mirrors backend/src/constants/ghanaTowns.js —
 * edit there first, then copy the data across, same as ghanaRegions.ts.
 */
export const GHANA_TOWNS_BY_REGION: Record<GhanaRegion, string[]> = {
  Ahafo: [
    'Goaso',
    'Kukuom',
    'Kenyasi',
    'Hwidiem',
    'Duayaw Nkwanta',
    'Bechem',
    'Mim',
    'Sankore',
    'Acherensua',
    'Kwapong',
  ],
  Ashanti: [
    'Kumasi',
    'Obuasi',
    'Ejisu',
    'Mampong',
    'Konongo',
    'Bekwai',
    'Effiduase',
    'Agona',
    'Asokore Mampong',
    'Offinso',
    'Tepa',
    'Juaso',
    'Kuntanase',
    'Bonwire',
    'Suame',
    'Asawase',
    'Tafo',
    'Manhyia',
    'Fumesua',
    'Ntonso',
    'Nkawie',
    'Jacobu',
    'Foase',
    'Antoa',
    'Atonsu',
    'Ahodwo',
    'Adum',
    'Kwadaso',
    'Asokwa',
    'New Edubiase',
    'Kokofu',
    'Feyiase',
    'Ejura',
    'Mankranso',
  ],
  Bono: [
    'Sunyani',
    'Berekum',
    'Dormaa Ahenkro',
    'Wenchi',
    'Nsoatre',
    'Odumase',
    'Chiraa',
    'Techimantia',
    'Sampa',
    'Japekrom',
    'Badu',
    'Seikwa',
    'Drobo',
  ],
  'Bono East': ['Techiman', 'Kintampo', 'Nkoranza', 'Atebubu', 'Yeji', 'Prang', 'Busunya', 'Amantin', 'Kwame Danso', 'Jema'],
  Central: [
    'Cape Coast',
    'Kasoa',
    'Winneba',
    'Elmina',
    'Saltpond',
    'Agona Swedru',
    'Mankessim',
    'Assin Fosu',
    'Twifo Praso',
    'Dunkwa-on-Offin',
    'Apam',
    'Anomabo',
    'Ajumako',
    'Breman Asikuma',
    'Abura Dunkwa',
    'Ekumfi Otuam',
    'Diaso',
    'Moree',
    'Komenda',
    'Nyanyano',
    'Gomoa Fetteh',
    'Gomoa Buduburam',
    'Assin Manso',
  ],
  Eastern: [
    'Koforidua',
    'Nkawkaw',
    'Akosombo',
    'Somanya',
    'Suhum',
    'Nsawam',
    'Akim Oda',
    'Akropong',
    'Aburi',
    'Mpraeso',
    'Kade',
    'Begoro',
    'Asamankese',
    'Kibi',
    'New Tafo',
    'Donkorkrom',
    'Anyinam',
    'Osino',
    'Nkurakan',
    'Adawso',
    'Akwatia',
    'Abetifi',
    'Kwabeng',
    'Asesewa',
    'Bunso',
  ],
  'Greater Accra': [
    'Accra',
    'Tema',
    'Madina',
    'Adenta',
    'Ashaiman',
    'Teshie',
    'Nungua',
    'Dansoman',
    'Kaneshie',
    'Achimota',
    'Dome',
    'Weija',
    'Amasaman',
    'Ningo-Prampram',
    'Prampram',
    'Dodowa',
    'Ada Foah',
    'Sege',
    'Kpone',
    'Afienya',
    'Spintex',
    'East Legon',
    'Osu',
    'La',
    'Jamestown',
    'Haatso',
    'Taifa',
    'Pokuase',
    'Ofankor',
    'Sowutuom',
    'Kwabenya',
    'Sakumono',
    'Ashongman',
    'Abokobi',
    'Ablekuma',
    'Kokrobite',
    'Bortianor',
    'Gbawe',
    'Mallam',
    'Dzorwulu',
    'Labone',
  ],
  'North East': ['Nalerigu', 'Walewale', 'Gambaga', 'Bunkpurugu', 'Chereponi', 'Yunyoo', 'Wulugu'],
  Northern: ['Tamale', 'Yendi', 'Savelugu', 'Tolon', 'Bimbilla', 'Gushegu', 'Kpandai', 'Karaga', 'Zabzugu', 'Kumbungu', 'Sang', 'Wulensi'],
  Oti: ['Dambai', 'Kete Krachi', 'Jasikan', 'Kadjebi', 'Nkwanta', 'Worawora', 'Chinderi', 'Kpassa', 'Kpeve', 'Nkonya'],
  Savannah: ['Damongo', 'Bole', 'Salaga', 'Sawla', 'Buipe', 'Daboya', 'Larabanga', 'Bamboi'],
  'Upper East': ['Bolgatanga', 'Bawku', 'Navrongo', 'Zebilla', 'Paga', 'Sandema', 'Bongo', 'Zuarungu', 'Garu', 'Pusiga'],
  'Upper West': ['Wa', 'Tumu', 'Lawra', 'Jirapa', 'Nadowli', 'Funsi', 'Nandom', 'Wechiau'],
  Volta: [
    'Ho',
    'Hohoe',
    'Keta',
    'Aflao',
    'Sogakope',
    'Kpando',
    'Anloga',
    'Denu',
    'Peki',
    'Adidome',
    'Akatsi',
    'Dzodze',
    'Kpetoe',
    'Ave Dakpa',
    'Abutia',
    'Anfoega',
  ],
  Western: [
    'Sekondi',
    'Takoradi',
    'Tarkwa',
    'Axim',
    'Prestea',
    'Bogoso',
    'Half Assini',
    'Elubo',
    'Shama',
    'Daboase',
    'Wassa Akropong',
    'Aboso',
    'Effia',
    'Kojokrom',
    'Anaji',
    'Agona Nkwanta',
    'Asankrangwa',
  ],
  'Western North': ['Sefwi Wiawso', 'Bibiani', 'Enchi', 'Juaboso', 'Akontombra', 'Sefwi Bekwai', 'Bodi', 'Dadieso'],
}

export function townsForRegion(region?: string) {
  if (!region) return []
  return GHANA_TOWNS_BY_REGION[region as GhanaRegion] || []
}

export function townOptionsForRegion(region?: string) {
  return townsForRegion(region).map((town) => ({ label: town, value: town }))
}

/** Sanity check that every canonical region has its own town list. */
export const GHANA_TOWNS_REGION_COVERAGE_OK = GHANA_REGIONS.every((region) => GHANA_TOWNS_BY_REGION[region]?.length > 0)
