export type ListingCategory = {
  label: string
  sizePlaceholder: string
}

export const LISTING_CATEGORIES: ListingCategory[] = [
  { label: 'Outerwear', sizePlaceholder: 'XS, S, M, L, XL, XXL' },
  { label: 'T-Shirts', sizePlaceholder: 'XS, S, M, L, XL, XXL' },
  { label: 'Shirts', sizePlaceholder: 'Collar 15, 16, M, L, XL' },
  { label: 'Hoodies & Sweatshirts', sizePlaceholder: 'S, M, L, XL, XXL' },
  { label: 'Sweaters & Knits', sizePlaceholder: 'S, M, L, XL' },
  { label: 'Dresses', sizePlaceholder: 'UK 6, UK 8, UK 10, UK 12' },
  { label: 'Skirts', sizePlaceholder: 'Waist 26, 28, 30 or S, M, L' },
  { label: 'Jeans', sizePlaceholder: 'W28 L30, W32 L32' },
  { label: 'Trousers', sizePlaceholder: 'W30, W32, W34 or S, M, L' },
  { label: 'Shorts', sizePlaceholder: 'S, M, L or W30' },
  { label: 'Sneakers', sizePlaceholder: 'UK 6, UK 7, UK 8, UK 9' },
  { label: 'Boots', sizePlaceholder: 'UK 6, UK 7, UK 8, UK 9' },
  { label: 'Sandals & Slides', sizePlaceholder: 'UK 5, UK 6, UK 7, UK 8' },
  { label: 'Bags', sizePlaceholder: 'Mini, Small, Medium, Large' },
  { label: 'Hats & Caps', sizePlaceholder: 'One size, 56cm, 58cm' },
  { label: 'Belts', sizePlaceholder: '30, 32, 34, 36 or S, M, L' },
  { label: 'Jewelry & Watches', sizePlaceholder: 'One size, ring 7, 18cm' },
  { label: 'Sunglasses', sizePlaceholder: 'One size' },
  { label: 'Sportswear', sizePlaceholder: 'S, M, L, XL or UK shoe size' },
  { label: 'Traditional & Prints', sizePlaceholder: 'S, M, L, custom measurements' },
  { label: 'Workwear', sizePlaceholder: 'S, M, L, XL or waist size' },
  { label: 'Designer', sizePlaceholder: 'Brand size, EU/UK size, or measurements' },
  { label: 'Vintage', sizePlaceholder: 'Tagged size plus measurements' },
  { label: 'Kids', sizePlaceholder: 'Age 2-3, 4-5, 6-7, 8-9' },
  { label: 'Accessories', sizePlaceholder: 'One size or dimensions' },
  { label: 'Wholesale Bales', sizePlaceholder: 'Bale count, grade, or pieces per bale' },
  { label: 'Fabric & Textiles', sizePlaceholder: 'Yards, meters, roll size' },
  { label: 'Other', sizePlaceholder: 'Size, fit, or measurements' },
]

export const LISTING_BRANDS = [
  'Adidas',
  'Air Jordan',
  'ASOS',
  'BAPE',
  'Bershka',
  'Birkenstock',
  'Boohoo',
  'Burberry',
  'Calvin Klein',
  'Carhartt',
  'Chanel',
  'Champion',
  'Clarks',
  'Columbia',
  'Converse',
  'COS',
  'Crocs',
  'Da Viva',
  'Diesel',
  'Dickies',
  'Dior',
  'Dr. Martens',
  'Fendi',
  'Fila',
  'Forever 21',
  'Gap',
  'GTP',
  'Gucci',
  'H&M',
  'Hermes',
  'Hugo Boss',
  'Jordan',
  'Lacoste',
  'Lee',
  "Levi's",
  'Louis Vuitton',
  'Mango',
  'Massimo Dutti',
  'New Balance',
  'Next',
  'Nike',
  'Old Navy',
  'Palace',
  'Patagonia',
  'Polo Ralph Lauren',
  'Prada',
  'Primark',
  'Pull&Bear',
  'Puma',
  'Reebok',
  'River Island',
  'Saint Laurent',
  'Shein',
  'Skechers',
  'Stussy',
  'Supreme',
  'The North Face',
  'Timberland',
  'Tommy Hilfiger',
  'Under Armour',
  'Unbranded',
  'Uniqlo',
  'Vans',
  'Versace',
  'Vlisco',
  'Woodin',
  'Wrangler',
  'Zara',
]

export const LISTING_CONDITIONS = ['excellent', 'great', 'good', 'fair', 'poor'] as const

export const LISTING_COLORS = [
  { hex: '#f5f0dc', label: 'Beige', value: 'beige' },
  { hex: '#000000', label: 'Black', value: 'black' },
  { hex: '#1179bd', label: 'Blue', value: 'blue' },
  { hex: '#8b5a2b', label: 'Brown', value: 'brown' },
  { hex: '#973131', label: 'Burgundy', value: 'burgundy' },
  { hex: '#fffdd0', label: 'Cream', value: 'cream' },
  { hex: '#00a6d6', label: 'Cyan', value: 'cyan' },
  { hex: '#d5b43f', label: 'Gold', value: 'gold' },
  { hex: '#49a900', label: 'Green', value: 'green' },
  { hex: '#8a8f98', label: 'Gray', value: 'gray' },
  { hex: '#fffff0', label: 'Ivory', value: 'ivory' },
  { hex: '#9c8a16', label: 'Khaki', value: 'khaki' },
  { hex: 'conic-gradient(#e10600, #ffcc00, #38b000, #1179bd, #5b20d6, #e10600)', label: 'Multi', value: 'multi' },
  { hex: '#002b5f', label: 'Navy', value: 'navy' },
  { hex: '#708238', label: 'Olive', value: 'olive' },
  { hex: '#ff6500', label: 'Orange', value: 'orange' },
  { hex: '#ed5aae', label: 'Pink', value: 'pink' },
  { hex: '#5b20d6', label: 'Purple', value: 'purple' },
  { hex: '#e10600', label: 'Red', value: 'red' },
  { hex: 'linear-gradient(135deg,#777,#f6f6f6)', label: 'Silver', value: 'silver' },
  { hex: '#008080', label: 'Teal', value: 'teal' },
  { hex: '#40e0d0', label: 'Turquoise', value: 'turquoise' },
  { hex: '#7f00ff', label: 'Violet', value: 'violet' },
  { hex: '#ffffff', label: 'White', value: 'white' },
  { hex: '#ffcc00', label: 'Yellow', value: 'yellow' },
] as const

export type ListingColor = (typeof LISTING_COLORS)[number]['value']

export function sizePlaceholderForCategory(category?: string) {
  return LISTING_CATEGORIES.find((item) => item.label === category)?.sizePlaceholder || 'M, L, XL, W32, UK 8...'
}
