export type AppRoute =
  | 'login'
  | 'authCallback'
  | 'register'
  | 'adminKyc'
  | 'adminKycDetail'
  | 'adminDisputes'
  | 'adminOverview'
  | 'newListing'
  | 'editListing'
  | 'browse'
  | 'freshDrops'
  | 'digishops'
  | 'bales'
  | 'topPicks'
  | 'shop'
  | 'retailDetail'
  | 'community'
  | 'eventDetail'
  | 'eventManage'
  | 'communityEventForm'
  | 'communityFinspoDetail'
  | 'communityFinspoForm'
  | 'saved'
  | 'profileSettings'
  | 'profile'
  | 'inbox'
  | 'cart'
  | 'checkout'
  | 'orderConfirmed'
  | 'orderDetail'
  | 'orderHistory'
  | 'orderManagement'
  | 'promotionReturn'
  | 'listingPromotions'
  | 'kyc'
  | 'openShop'
  | 'wallet'
  | 'manageShop'
  | 'home'

export function resolveRoute(pathname: string, search: string): AppRoute {
  const searchParams = new URLSearchParams(search)

  if (pathname.startsWith('/auth/callback')) return 'authCallback'
  if (pathname.startsWith('/login')) return 'login'
  if (pathname.startsWith('/register')) return 'register'
  if (/^\/admin\/kyc\/[^/]+/.test(pathname)) return 'adminKycDetail'
  if (pathname.startsWith('/admin/kyc')) return 'adminKyc'
  if (pathname.startsWith('/admin/disputes')) return 'adminDisputes'
  if (pathname.startsWith('/admin')) return 'adminOverview'
  if (pathname.startsWith('/top-picks')) return 'topPicks'
  if (pathname.startsWith('/fresh-drops')) return 'freshDrops'
  if (pathname.startsWith('/digishops')) return 'digishops'
  if (pathname.startsWith('/bales') || pathname.startsWith('/bale-wholesale')) return 'bales'
  if (pathname.startsWith('/browse')) return 'browse'
  if (pathname.startsWith('/shops/')) return 'shop'
  if (pathname.startsWith('/listings/new')) return 'newListing'
  if (/^\/listings\/[^/]+\/edit/.test(pathname)) return 'editListing'
  if (pathname.startsWith('/listing')) return 'retailDetail'
  if (pathname.startsWith('/community/events/new') || /^\/community\/events\/[^/]+\/edit/.test(pathname)) return 'communityEventForm'
  if (/^\/community\/events\/[^/]+\/manage/.test(pathname)) return 'eventManage'
  if (/^\/community\/events\/[^/]+/.test(pathname)) return 'eventDetail'
  if (pathname.startsWith('/community/finspo/new') || /^\/community\/finspo\/[^/]+\/edit/.test(pathname)) return 'communityFinspoForm'
  if (/^\/community\/finspo\/[^/]+/.test(pathname)) return 'communityFinspoDetail'
  if (pathname.startsWith('/community')) return 'community'
  if (pathname.startsWith('/saved')) return 'saved'
  if (pathname.startsWith('/profile/settings')) return 'profileSettings'
  if (pathname.startsWith('/profile')) return 'profile'
  if (pathname.startsWith('/inbox')) return 'inbox'
  if (pathname.startsWith('/cart')) return 'cart'
  if (pathname.startsWith('/checkout')) return 'checkout'
  if (pathname.startsWith('/order-confirmed')) return 'orderConfirmed'
  if (pathname.startsWith('/promotions/confirm')) return 'promotionReturn'
  if (pathname.startsWith('/manage-shop/promotions')) return 'listingPromotions'
  if (/^\/orders\/[^/]+/.test(pathname) && !pathname.startsWith('/orders/history')) return 'orderDetail'
  if (pathname.startsWith('/orders/history')) return 'orderHistory'
  if (pathname.startsWith('/manage-shop/orders/history')) return 'orderHistory'
  if (pathname.startsWith('/manage-shop/orders')) return 'orderManagement'
  if (pathname === '/orders') return 'orderManagement'
  if (pathname.startsWith('/orders')) return 'orderManagement'
  if (pathname.startsWith('/account/kyc')) return 'kyc'
  if (pathname.startsWith('/kyc')) return 'kyc'
  if (pathname.startsWith('/open-shop')) return 'openShop'
  if (pathname.startsWith('/wallet')) return 'wallet'
  if (pathname.startsWith('/manage-shop')) return 'manageShop'
  if (pathname.startsWith('/dashboard') && searchParams.get('view') === 'shop') return 'manageShop'
  if (pathname.startsWith('/dashboard')) return 'home'

  return 'home'
}
